### PR TITLE
gjoel m1

### PR DESCRIPTION
**Pull request by datahaki**

### CODE REVIEW

**Review by JoelGaechter — APPROVED** [review]
Is there the intention to bring back the tests, or leave them away?

**Comment by datahaki** [comment]
@JoelGaechter i have updated the tests and extended the PlotDemo. please check PlotDemo: when i leave out the labels, only 1 visual row is shown (instead of 2).

**Comment by JoelGaechter** [comment]
happens since in the datasets they are saved under their label's string which in that case is the same ("")
can be fixed by using getLabel instead of getLabelString; however this is not possible for TableXYDataset as you can seein the demo's line/stackedline

**Comment by datahaki** [comment]
i fixed the ListPlot using @fluric code. however the legend is still incorrect.

**Comment by JoelGaechter** [comment]
That fix is unnecessary!
All it changes is that if the label is empty it gets replaced by the equivalent of the row index.
Otherwise I'd stick with XYTable instead of XYSeries, as it also works for stacked.
Not sure about the clips. People can set the ranges for the charts anyway if they want, it might be more convinient though.

**Comment by JoelGaechter** [comment]
more in line with API changes
still ugly but probably necessary due to limitations by JFree in CategoryTableXYDataset to only allow String keys

**Comment by datahaki** [comment]
your solution is nice!
in my last commits I just moved some functions around

**Comment by datahaki** [comment]
i suspect that the function `naming` in `Histogram` is not performing correctly.
please have a look at `SkewPlotDemo`, `NumericPlotDemo`, `ListPlotDemo`

**Pull request merged**
